### ISSUE TITLE
Requirements check re-order

### ISSUE THREAD

**Issue by nateswart** [nateswart/lunchbox#16]
While testing this from a brand new machine with no pre-reqs installed, I noticed the vagrant plugins were being checked for before vagrant itself was checked for. It should be the other way around, since the plugin cant be resolved until vagrant itself is installed.

![vagrant-hostsupdater](https://cloud.githubusercontent.com/assets/839888/11610212/a1dc8858-9b69-11e5-86d4-f44e44cdb370.png)

**Comment by yuriybabenko** [comment]
Ah, yes. Dependencies are currently ran independent of each other via separate promises. I'll refactor that for sequential execution.

**Comment by yuriybabenko** [comment]
Issue fixed in the latest PR. There's now a new 'qchain' module (wrapper for npm's Q) in place that provides a standardized way of building promise chains, and allows the chain to be executed sequentially or not.
