### ISSUE TITLE
Ensure vagrant-hostsupdater plugin is installed

### ISSUE THREAD

**Issue by nateswart** [nateswart/lunchbox#7]
On launch, detect (and optionally offer to install if missing) the vagrant-hostsupdater plugin

**Comment by thom8** [comment]
@nateswart you can use something like this -->

```
%x(vagrant plugin install vagrant-hostsupdater) unless Vagrant.has_plugin?('vagrant-hostsupdater')
```

**Comment by thom8** [comment]
However you might find issues with Windows support RE: https://github.com/nateswart/lunchbox/issues/6

**Comment by yuriybabenko** [comment]
I've added a dependency check for this plugin to the latest PR. Issue can be closed after that merge.
