### ISSUE TITLE
Investigate if vagrant-vbguest is needed?

### ISSUE THREAD

**Issue by nateswart** [nateswart/lunchbox#8]
I'm unsure if vagrant-vbguest is needed (or even just advisable). If so, it should be detected for and optionally offered to be installed.

**Comment by geerlingguy** [comment]
It's good to have in general; if a box provider gets a little lazy, people with newer versions of VirtualBox often end up getting funny errors until the box is updated upstream. In my case, my boxes are still built for 5.0.4 while 5.0.8 has been around a few weeks.

**Comment by nateswart** [comment]
Ok, I'll add a check for this. Or more accurately, I'll ask @yuriybabenko ... can you add a check for this?  :)

**Comment by yuriybabenko** [comment]
Thanks for the quick merge, @nateswart. I think we can close this one.

**Comment by nateswart** [comment]
Agreed - thanks for the PR!
